### ISSUE TITLE
Not Working When Ran via Docker

### ISSUE THREAD

**Issue by atb-brown** [karthiksai231/docker-example#1]
I apologize, but I'm not an expert in Docker. But I tried running this application directly via the jar and it worked fine. However, when I try to run it via Docker, it does not work.

When I try `docker-compose up`, it fails completely. When I try to run the mongo container and the app container separately, they both start up, but I get the following error in the app container logs:
```
2021-01-21 19:13:12.247 INFO 1 --- [localhost:27017] org.mongodb.driver.cluster : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
   at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70) ~[mongodb-driver-core-4.0.4.jar!/:na]
   at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:127) ~[mongodb-driver-core-4.0.4.jar!/:na]
   at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-4.0.4.jar!/:na]
   at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
   at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
   at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:na]
   at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:na]
   at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:na]
   at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
   at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
   at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:63) ~[mongodb-driver-core-4.0.4.jar!/:na]
   at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79) ~[mongodb-driver-core-4.0.4.jar!/:na]
   at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[mongodb-driver-core-4.0.4.jar!/:na]

... 3 common frames omitted
```

Even though that exception shows up in the app container logs, the container remains running and I get `500` internal server errors when making requests. I'm guessing it's due to the mongo connection failing?

**Comment by karthiksai231** [comment]
Hi @atb-brown 
Yes I think the issue your are seeing is related to mongo access but I have fixed the docker compose issue. Please pull the latest changes and retry. 
https://github.com/karthiksai231/docker-example/pull/2/files

**Comment by atb-brown** [comment]
Hi @karthiksai231 

Thanks for responding and looking into fixing this. I pulled your latest changes and, unfortunately, I'm still seeing the same issue. Do you have any ideas for how I should try and investigate it assuming you're unable to recreate the issue?

**Comment by karthiksai231** [comment]
Hi @atb-brown 
Can you please post the repro steps and the error message on your console?
